version: '3.7'
services:
  dev:
    container_name: tta-elastic
    build:
      context: .
    image: tta-elastic
    ports:
      - 8080:8080
    command: npm run dev
    stdin_open: true
    tty: true
    user: root

  test:
    build:
      context: .
    command: npm test
